server:
  port: 8082

spring:
  application:
    name: zk-consumer
  cloud:
    inetutils:
      preferredNetworks:
        - 10
    zookeeper:
      connect-string: 192.168.56.121:2181,192.168.56.121:2182,192.168.56.121:2183
      discovery:
        enabled: true
        register: true
        root: /micro-service/
        instance-host: ${spring.cloud.client.ip-address}